version: '3'

services:
  db:
    container_name: nextcloud-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    image: mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  app:
    container_name: nextcloud-app
    depends_on:
      - db
    environment:
      - NETWORK_ACCESS=${NETWORK_ACCESS}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    expose:
      - 80
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro

volumes:
  nextcloud:
  db:

networks:
  default:
    external:
      name: nginx-proxy
